config/routes.rb
Rails.application.routes.draw do

  get 'carts/show'

    root 'static_pages#home'
    get  '/help',    to: 'static_pages#help'
    get  '/about',   to: 'static_pages#about'
    get  '/contact', to: 'static_pages#contact'
    get  '/signup',  to: 'users#new'
    post '/signup',  to: 'users#create'
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    resources :users do
      get 'cart', to: 'carts#show'
    end

    resources :carts


    resources :hotels do
      post 'add_to_cart', to: "hotels#add_to_cart"

    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :hotel
  belongs_to :user
end

app/models/hotel.rb
class Hotel < ApplicationRecord
 has_many :hotel_views
end

app/models/hotel_view.rb
class HotelView < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :hotel
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_one :cart ,dependent: :destroy
  has_many :hotel_views , dependent: :destroy

  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  private
  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def create
  end

  def show

 @hotels = Hotel.where(id: Cart.where(user_id: current_user.id ).map(&:hotel_id))

  end

  def destroy
    Cart.find(user_id: current_user.id , hotel_id: params[:id]).destroy

    redirect_to cart_path(cart)
  end


end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :logged_in_user, only: [:add_to_cart,:index,:show]
  def index
    @hotels = Hotel.paginate(page: params[:page])
  end

  def show
    @hotel=Hotel.find(params[:id])
    view=HotelView.new(user_id: current_user.id , hotel_id: @hotel.id, rating: @hotel.rating )
    view.save
    @count=HotelView.where(hotel_id: @hotel.id).count
  end

  def add_to_cart
    @hotel=Hotel.find_by(id: params[:hotel_id])
    @check = Cart.find_by(hotel_id: params[:hotel_id] ,user_id: current_user.id )
    if @check.nil?
        cart=Cart.new(user_id: current_user.id , hotel_id: params[:hotel_id] ,is_current: true)
        cart.save
    end
    redirect_to cart_path(current_user)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
   if user && user.authenticate(params[:session][:password])
     # Log the user in and redirect to the user's show page.
     log_in user
      redirect_back_or user
   else
   # Create an error message.
    flash.now[:danger] = 'Invalid email/password combination'
   render 'new'
  end
 end



    def destroy
      log_out
      redirect_to root_url
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :logged_in_user, only: [:destroy,:index,:edit, :update]
      before_action :correct_user,   only: [:edit, :update]
      before_action :admin_user,     only: :destroy
  def new
       @user = User.new
  end

  def show
     @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # Handle a successful save.
       flash[:success] = "Welcome to the Sample App!"
       log_in @user
        redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end


  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      # Handle a successful update.
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
   @users = User.paginate(page: params[:page])
  end

  def destroy
    User.find(params[:id]).destroy
   flash[:success] = "User deleted"
   redirect_to users_url
  end


  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # Before filters



    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # Confirms an admin user.
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
  def current_hotel
    @current_hotel ||= Hotel.find_by(id: session[:hotel_id])
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
 def log_in(user)
   session[:user_id] = user.id
 end

 # Returns the current logged-in user (if any).
 def current_user
   @current_user ||= User.find_by(id: session[:user_id])
 end

 # Returns true if the user is logged in, false otherwise.
 def logged_in?
   !current_user.nil?
 end

 # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

# Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Redirects to stored location (or to the default).
 def redirect_back_or(default)
   redirect_to(session[:forwarding_url] || default)
   session.delete(:forwarding_url)
 end

 # Stores the URL trying to be accessed.
 def store_location
   session[:forwarding_url] = request.original_url if request.get?
 end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/show.html.erb
<div class="jumbotron text-center">
  <h1>My Cart</h1>
</div>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h3>
        <% @hotels.each do |hotel| %>
           <li><%= hotel.name %> | <%= hotel.price %></li>
        <% end %>
      </h3>
      <%= link_to "Checkout", '' , class: "btn btn-lg btn-primary" %>
    </section>
  </aside>
</div>

app/views/hotels/index.html.erb
<h1>All Hotels</h1>
<%= will_paginate %>
<ul class="hotels">
  <% @hotels.each do |hotel| %>
    <li>
      <%= link_to hotel.name, hotel %>
      |Address-<%= hotel.address %>
    |Price-<%= hotel.price %>
      |Rating-<%= hotel.rating %>

    </li>
  <% end %>
</ul>
<%= will_paginate %>

app/views/hotels/show.html.erb
<div class="row">

</div>
<%= @hotel.name %><%= @hotel.address %>
<h2>This hotel has been visited <span class = "label label-default">
  <%= @count %>
 </span></h2>
<aside class="col-md-4"
<div>
<%= link_to "Add to cart", hotel_add_to_cart_path(hotel_id: @hotel.id) , method: :post ,class: "btn btn-lg btn-primary"  %>
</div>
</aside>

</div>

<!-- <h3 class=>This hotel has benn visited <span></span>times</h3> -->

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Hotel app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <% if logged_in? %>
          <% if current_user.admin? %>
          <li><%= link_to "Users", users_path %></li>
          <% end %>
          <li><%= link_to "Hotels", hotels_path %></li>
          <li><%= link_to "Cart", cart_path(current_user) %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>


<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hotel App</title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>

    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<h1>About</h1>
<p>
  
</p>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<p>

</p>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>
  
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Hotel Booking App</h1>

  <h2>
    This is the home page for the Hotel Booking
    sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>All users</h1>
<%= will_paginate %>
<ul class="users">
  <%= render @users %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
     <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.name %>
          </h1>
    </section>
  </aside>
</div>